#!/bin/bash

require_deployment_dir() {
  if [ -z ${DEPLOYMENT_DIR} ] || [ ! -d ${DEPLOYMENT_DIR} ]; then
    set +x
    echo '$DEPLOYMENT_DIR must be set to your deployment directory'
    exit 1
  fi
}

require_aws_environment() {
  set +x
  source ${DEPLOYMENT_DIR}/aws_environment

  if [ -z ${AWS_DEFAULT_REGION} ]; then
    echo 'AWS_DEFAULT_REGION is not set'
    exit 1
  fi

  if [ -z ${AWS_ACCESS_KEY_ID} ]; then
    echo 'AWS_DEFAULT_REGION is not set'
    exit 1
  fi

  if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
    echo 'AWS_DEFAULT_REGION is not set'
    exit 1
  fi

  require_aws_environment() { : ; } # Rash's dirty memoisation. Makes the function a no-op

  set -x
}

require_bosh_environment() {
  set +x
  source ${DEPLOYMENT_DIR}/bosh_environment

  if [ -z ${BOSH_USER} ]; then
    echo 'BOSH_USER is not set'
    exit 1
  fi

  if [ -z ${BOSH_PASSWORD} ]; then
    echo 'BOSH_PASSWORD is not set'
    exit 1
  fi

  if [ -z ${BOSH_DIRECTOR} ]; then
    echo 'BOSH_DIRECTOR is not set'
    exit 1
  fi
  set -x

  require_bosh_environment() { : ; } # Rash's dirty memoisation. Makes the function a no-op

}

require_command() {
  command -v $1 >/dev/null || { echo "$1 is required"; exit 1; }
}