#!/bin/bash

set -e -x

script_dir=$(dirname $0)

source ${script_dir}/lib/deployment_utils

require_deployment_dir

source ${DEPLOYMENT_DIR}/bosh_environment

bosh_ip=$(echo ${BOSH_DIRECTOR} | awk -F/ '{print $3}' | awk -F: '{print $1}')

keypair_path=${DEPLOYMENT_DIR}/artifacts/keypair/id_rsa_bosh

chmod 600 ${keypair_path}
ssh-add ${keypair_path}
ssh -A vcap@${bosh_ip}
