#!/bin/bash

############
# SETUP

set -e +x
scripts_dir=$(cd $(dirname $0)/..; pwd)
source ${scripts_dir}/lib/dependencies
source ${scripts_dir}/lib/concourse

############

require_command jq
require_command yaml2json

require_deployment_dir
require_concourse_api_target

fly -t cli c main -c ${scripts_dir}/../pipelines/main.yml \
  --vars-from ${DEPLOYMENT_DIR}/pipeline_vars/cli_asset_buckets.yml \
  --vars-from ${DEPLOYMENT_DIR}/pipeline_vars/github_keys.yml \
  --vars-from ${DEPLOYMENT_DIR}/pipeline_vars/dockerhub_credentials.yml

