#!/bin/bash

############
# SETUP

set -e +x
scripts_dir=$(cd $(dirname $0)/..; pwd)
source ${scripts_dir}/lib/dependencies
source ${scripts_dir}/lib/concourse

############

require_command jq
require_command yaml2json

require_deployment_dir

require_concourse_api_target

### Get api credentials
usage_api_credentials() {
  set +x
  echo "This script requires ${atc_credentials_file} to exist,"
  echo "  and contain a values for basic_auth_username and basic_auth_password"
  echo
  echo "  Error: ${1}"
  exit 1
}

atc_credentials_file=${DEPLOYMENT_DIR}/stubs/concourse/atc_credentials.yml


if [ ! -f ${atc_credentials_file} ]; then
  usage_api_credentials "${atc_credentials_file} not found"
fi

atc_username=`cat ${atc_credentials_file} | yaml2json | jq -r .atc_credentials.basic_auth_username`

if [ -z "${atc_username}" ] || [ "${atc_username}" == "null" ]; then
  usage_api_credentials "basic_auth_username not set"
fi


atc_password=`cat ${atc_credentials_file} | yaml2json | jq -r .atc_credentials.basic_auth_password`

if [ -z "${atc_password}" ] || [ "${atc_password}" == "null" ]; then
  usage_api_credentials "basic_auth_password not set"
fi

fly save-target cli --api https://${api_target} --username ${atc_username} --password ${atc_password}

echo "forcing a newline, see https://github.com/concourse/fly/issues/26"
cat ~/.flyrc

echo
echo "Use \`fly -t cli <command>\` to run fly with this target selected"